//Display name, Q, W, E, R, notes
//"Yes", "Maybe", "No"
var lastUpdated = "Patch 5.11, June 18, 2015";
var championData = [
["Aatrox", "Yes", "No", "Yes", "No", ""],
["Ahri", "Yes", "No", "Yes", "Yes", ""],
["Akali", "No", "Yes", "No", "Yes", ""],
["Alistar", "Yes", "Yes", "Yes", "Yes", ""],
["Amumu", "Yes", "No", "No", "Yes", "Levelling E is allowed; using its active is not"],
["Anivia", "Yes", "Yes", "No", "Yes", ""],
["Annie", "Maybe", "Maybe", "Yes", "Maybe", "You may use your ulti to block skillshots. You may use your Q, W, or R if you have stun (from E)"],
["Ashe", "No", "Yes", "No", "Yes", "Q may not be used to proc the slow"],
["Azir", "Yes", "Yes", "Yes", "Yes", "This is an exception to the 'no combo CC' rule"],
["Bard", "Yes", "Yes", "Yes", "Yes", ""],
["Blitzcrank", "Yes", "Yes", "Yes", "Yes", ""],
["Brand", "No", "No", "No", "No", "You may NOT use abilities to proc Brand's passive and stun"],
["Braum", "Yes", "Yes", "Yes", "Yes", "You cannot auto attack to proc your passive"],
["Caitlyn", "No", "Yes", "Yes", "No", ""],
["Cassiopeia", "Contested", "Yes", "No", "Yes", "Q procs movespeed bonus but only if it hits a champion. Also, 'Cassiopeia' is surprisingly hard to spell"],
["Cho'Gath", "Yes", "Yes", "No", "No", ""],
["Corki", "No", "Yes", "No", "No", ""],
["Darius", "No", "Yes", "Yes", "No", ""],
["Diana", "No", "Yes", "Yes", "Yes", "hail the moon"],
["Dr. Mundo", "Yes", "Yes", "No", "Yes", ""],
["Draven", "No", "Yes", "Yes", "No", "Q may not be used to refresh W"],
["Ekko", "Yes", "Yes", "Yes", "Yes", ""],
["Elise (Human)", "No", "No", "Yes", "Yes", ""],
["Elise (Spider)", "Yes", "No", "Yes", "Yes", ""],
["Evelynn", "No", "Yes", "No", "Yes", "PERMABANNED for both Hiders and Seekers. May not kill for a reset on W (unless the seeker has stayed in the field for an extended period of time at low health)"],
["Ezreal", "No", "No", "Yes", "No", ""],
["Fiddlesticks", "Yes", "No", "Yes", "Yes", ""],
["Fiora", "Yes", "Yes", "No", "Yes", "Cannot autoattack to activate E's movespeed bonus"],
["Fizz", "Yes", "No", "Yes", "Yes", ""],
["Galio", "Yes", "Yes", "Yes", "Yes", ""],
["Gangplank", "No", "Yes", "Yes", "Yes", ""],
["Garen", "Yes", "Yes", "No", "No", ""],
["Gnar (Mini)", "Yes", "No", "Yes", "N/A", ""],
["Gnar (Mega)", "Yes", "Yes", "Yes", "Yes", ""],
["Gragas", "Yes", "Contested", "Yes", "Yes", "W may proc passive"],
["Graves", "No", "Yes", "Yes", "No", "Cannot autoattack to reduce his dash's cooldown"],
["Hecarim", "No", "No", "Yes", "Yes", ""],
["Heimerdinger", "Maybe", "No", "Yes", "Maybe", "Q can only be used to block skillshots. R can only be used on Q and R"],
["Irelia", "Yes", "No", "Yes", "No", ""],
["Janna", "Yes", "Yes", "Yes", "Yes", ""],
["Jarvan IV", "Maybe", "Yes", "Maybe", "Yes", "EQ may only be used in conjunction with each other"],
["Jax", "Yes", "No", "Yes", "Yes", ""],
["Jayce (Melee)", "Yes", "No", "Yes", "Yes", ""],
["Jayce (Ranged)", "No", "No", "Yes", "Yes", ""],
["Jinx", "No", "Yes", "Yes", "No", ""],
["Kalista", "Yes", "No", "No", "Yes", "PERMABANNED for both Hiders and Seekers"],
["Karma", "Maybe", "Yes", "Yes", "Yes", "Karma can only use her Q when empowered"],
["Karthus", "No", "Yes", "No", "No", ""],
["Kassadin", "Yes", "No", "Yes", "Yes", "PERMABANNED for both Hiders and Seekers"],
["Katarina", "No", "Yes", "Yes", "No", ""],
["Kayle", "Yes", "Yes", "No", "Yes", ""],
["Kennen", "No", "No", "Yes", "No", "Kennen cannot proc his passive"],
["Kha'Zix", "No", "Yes", "Yes", "Yes", ""],
["Kog'Maw", "No", "No", "Yes", "No", ""],
["Leblanc", "No", "Yes", "Yes", "Yes", ""],
["Lee Sin", "Yes", "Yes", "Yes", "Yes", ""],
["Leona", "Yes", "Yes", "Yes", "Yes", "praise the sun"],
["Lissandra", "Yes", "Yes", "Yes", "Yes", ""],
["Lucian", "No", "No", "Yes", "No", ""],
["Lulu", "Yes", "Yes", "Yes", "Yes", "Cannot use E on an enemy"],
["Lux", "Yes", "Yes", "Yes", "No", ""],
["Malphite", "Yes", "Yes", "Yes", "Yes", ""],
["Malzahar", "Yes", "Yes", "Yes", "Yes", "W can be used to spawn a voidling and block skillshots"],
["Maokai", "Yes", "Yes", "Yes", "Yes", ""],
["Miss Fortune", "No", "No", "Yes", "No", ""],
["Mordekaiser", "Contested", "Yes", "Contested", "Contested", "Abilities proc passive, which give him an absorption shield"],
["Morgana", "Yes", "No", "Yes", "Yes", ""],
["Nami", "Yes", "Yes", "No", "Yes", ""],
["Nautilus", "Yes", "Yes", "Yes", "Yes", ""],
["Nasus", "No", "Yes", "Yes", "Yes", "woof"],
["Nidalee (Cougar)", "No", "Yes", "No", "Yes", ""],
["Nidalee (Human)", "No", "No", "Yes", "Yes", ""],
["Nocturne", "Yes", "Yes", "Yes", "Yes", ""],
["Nunu", "Yes", "Yes", "Yes", "Yes", "Realize that you can only use your Q if the enemy team has a pet (such as Malzahar's Voidlings)"],
["Olaf", "Yes", "No", "No", "Yes", ""],
["Orianna", "Yes", "Yers", "Yes", "Yes", "Q can be used to reposition the ball for a W or R"],
["Pantheon", "No", "Yes", "No", "Yes", ""],
["Poppy", "No", "Yes", "Yes", "Yes", ""],
["Quinn (Human)", "Yes", "No", "Yes", "Yes", ""],
["Quinn (Valor)", "Yes", "No", "Yes", "Yes", ""],
["Rammus", "Yes", "Yes", "Yes", "No", ""],
["Rek'Sai", "No", "Yes", "No", "Yes", "PERMABANNED for both Hiders and Seekers"],
["Rek'Sai (burrowing)", "No", "Yes", "Yes", "Yes", "PERMABANNED for both Hiders and Seekers"],
["Renekton", "No", "Yes", "Yes", "Yes", ""],
["Rengar", "No", "Yes", "Yes", "Yes", "PERMABANNED for seekers"],
["Riven", "Yes", "Yes", "Yes", "No", ""],
["Rumble", "No", "Yes", "Yes", "Yes", ""],
["Ryze", "No", "Yes", "No", "Yes", ""],
["Sejuani", "Yes", "No", "No", "Yes", ""],
["Shaco", "Yes", "Yes", "Yes", "Yes", ""],
["Shen", "No", "Yes", "Yes", "Yes", ""],
["Shyvana (Human)", "No", "Yes", "No", "Yes", "Cannot autoattack to generate fury"],
["Shyvana (Dragon)", "No", "Yes", "No", "N/A", "Cannot autoattack to generate fury or extend Burnout's duration"],
["Singed", "No", "Yes", "Yes", "Yes", ""],
["Sion", "Yes", "Yes", "Yes", "Yes", ""],
["Sivir", "No", "No", "Yes", "Yes", ""],
["Skarner", "No", "Yes", "Yes", "Yes", "Skarner may not stack his Q"],
["Sona", "No", "Yes", "Yes", "Yes", ""],
["Soraka", "Yes", "Yes", "Yes", "Yes", ""],
["Swain", "Yes", "Yes", "No", "No", ""],
["Syndra", "No", "Yes", "Yes", "No", "Use your W on Malzahar's voidlings or something, I don't know. You chose Syndra, not me"],
["Talon", "No", "Yes", "Yes", "Yes", ""],
["Taric", "Yes", "No", "Yes", "No", "Levelling W is allowed; using its active is not"],
["Teemo", "Yes", "Yes", "No", "Yes", "PERMABANNED for Hiders"],
["Thresh", "Yes", "Yes", "Yes", "Yes", ""],
["Tristana", "No", "Yes", "No", "No", "You may not kill for a reset on W (unless the seeker has stayed in the field for an extended period of time at low health)"],
["Trundle", "Yes", "Yes", "Yes", "Yes", ""],
["Tryndamere", "Yes", "Yes", "Yes", "Yes", ""],
["Twisted Fate", "No", "Yes", "No", "Yes", "Try not picking a blue card, mkay?"],
["Twitch", "Yes", "Yes", "No", "No", ""],
["Udyr", "No", "Yes", "Yes", "No", "Udyr may auto attack to proc his E stun"],
["Urgot", "Contested", "Yes", "Contested", "No", "Q procs passive, which reduces damage dealt by 15%. It's a mini-exhaust."],
["Vayne", "Yes", "No", "Yes", "Yes", ""],
["Varus", "No", "No", "Yes", "Yes", ""],
["Veigar", "No", "Yes", "No", "No", ""],
["Vel'Koz", "Yes", "No", "Yes", "No", ""],
["Vi", "Yes", "No", "No", "Yes", ""],
["Viktor", "Yes", "Yes", "No", "No", ""],
["Vladimir", "No", "Yes", "No", "No", ""],
["Volibear", "Yes", "No", "Yes", "No", ""],
["Warwick", "No", "No", "Yes", "Yes", ""],
["Wukong", "No", "Yes", "Yes", "Yes", ""],
["Xin Zhao", "Yes", "No", "Yes", "Yes", ""],
["Xerath", "No", "Yes", "Yes", "No", ""],
["Yasuo", "No", "Yes", "Yes", "No", "You cannot use your Q to stack whirlwind"],
["Yorick", "Contested", "Yes", "Contested", "Yes", "Q and E proc his passive, which reduces damage taken"],
["Zac", "Yes", "No", "Yes", "Yes", ""],
["Zed", "No", "Yes", "Yes", "Yes", ""],
["Ziggs", "No", "Yes", "Yes", "No", ""],
["Zilean", "No", "Yes", "Yes", "Yes", ""],
["Zyra", "No", "Yes", "yes", "Yes", ""]
];